language: node_js
node_js:
  - '10'
script:
  - yarn compile
  - './create_app_yaml.sh'
deploy:
  provider: gae
  keyfile: key.json
  project: swsad-cloud
  # on:
  #   tags: true
before_install:
  - openssl aes-256-cbc -K $encrypted_948d23443eed_key -iv $encrypted_948d23443eed_iv
    -in key.json.enc -out key.json -d
